///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WPDockerDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginToWordpress recording.
    /// </summary>
    [TestModule("36bd94f2-adab-4019-8644-169c791e2c9b", ModuleType.Recording, 1)]
    public partial class LoginToWordpress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WPDockerDemoRepository repository.
        /// </summary>
        public static WPDockerDemoRepository repo = WPDockerDemoRepository.Instance;

        static LoginToWordpress instance = new LoginToWordpress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginToWordpress()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginToWordpress Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking WaitForDocumentLoaded() on item 'WordPressInstallation'.", repo.WordPressInstallation.SelfInfo, new RecordItemIndex(0));
            repo.WordPressInstallation.Self.WaitForDocumentLoaded();
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Value to 'rx' on item 'WordPressInstallation.UserLogin'.", repo.WordPressInstallation.UserLoginInfo, new RecordItemIndex(2));
            repo.WordPressInstallation.UserLogin.Element.SetAttributeValue("Value", "rx");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.UserPass' at Center.", repo.WordPressInstallation.UserPassInfo, new RecordItemIndex(3));
            repo.WordPressInstallation.UserPass.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rx' with focus on 'WordPressInstallation.UserPass'.", repo.WordPressInstallation.UserPassInfo, new RecordItemIndex(4));
            repo.WordPressInstallation.UserPass.PressKeys("rx");
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPressInstallation.Self, false, new RecordItemIndex(5));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.WpSubmit' at 41;18.", repo.WordPressInstallation.WpSubmitInfo, new RecordItemIndex(6));
            //repo.WordPressInstallation.WpSubmit.Click("41;18");
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking PerformClick() on item 'WordPressInstallation.WpSubmit'.", repo.WordPressInstallation.WpSubmitInfo, new RecordItemIndex(7));
            repo.WordPressInstallation.WpSubmit.PerformClick();
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking WaitForDocumentLoaded() on item 'WordPressInstallation'.", repo.WordPressInstallation.SelfInfo, new RecordItemIndex(8));
            repo.WordPressInstallation.Self.WaitForDocumentLoaded();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Welcome to WordPress!') on item 'WordPressInstallation.WelcomeToWordPress'.", repo.WordPressInstallation.WelcomeToWordPressInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.WordPressInstallation.WelcomeToWordPressInfo, "InnerText", "Welcome to WordPress!");
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPressInstallation.Self, false, new RecordItemIndex(10));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
