///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WPDockerDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LogoutWordpress recording.
    /// </summary>
    [TestModule("f01c1088-e97b-4fa4-a3c7-708fcfa62c4e", ModuleType.Recording, 1)]
    public partial class LogoutWordpress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WPDockerDemoRepository repository.
        /// </summary>
        public static WPDockerDemoRepository repo = WPDockerDemoRepository.Instance;

        static LogoutWordpress instance = new LogoutWordpress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LogoutWordpress()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LogoutWordpress Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'WordPressInstallation.HowdyRx' at Center.", repo.WordPressInstallation.HowdyRxInfo, new RecordItemIndex(0));
            repo.WordPressInstallation.HowdyRx.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.LogOut' at Center.", repo.WordPressInstallation.LogOutInfo, new RecordItemIndex(1));
            repo.WordPressInstallation.LogOut.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='You are now logged out.') on item 'WordPressInstallation.PTagYouAreNowLoggedOut'.", repo.WordPressInstallation.PTagYouAreNowLoggedOutInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.WordPressInstallation.PTagYouAreNowLoggedOutInfo, "InnerText", "You are now logged out.");
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPressInstallation.Self, false, new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
