///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WPDockerDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetupWordpress recording.
    /// </summary>
    [TestModule("81ce6f37-a281-4776-b1d2-c5204de1eacd", ModuleType.Recording, 1)]
    public partial class SetupWordpress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WPDockerDemoRepository repository.
        /// </summary>
        public static WPDockerDemoRepository repo = WPDockerDemoRepository.Instance;

        static SetupWordpress instance = new SetupWordpress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetupWordpress()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetupWordpress Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking PerformClick() on item 'WordPressInstallation.EnglishUnitedStates'.", repo.WordPressInstallation.EnglishUnitedStatesInfo, new RecordItemIndex(0));
            repo.WordPressInstallation.EnglishUnitedStates.PerformClick();
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking PerformClick() on item 'WordPressInstallation.LanguageContinue'.", repo.WordPressInstallation.LanguageContinueInfo, new RecordItemIndex(1));
            repo.WordPressInstallation.LanguageContinue.PerformClick();
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Value to 'Test' on item 'WordPressInstallation.WeblogTitle'.", repo.WordPressInstallation.WeblogTitleInfo, new RecordItemIndex(2));
            repo.WordPressInstallation.WeblogTitle.Element.SetAttributeValue("Value", "Test");
            
            //Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Value to 'rx' on item 'WordPressInstallation.UserLogin'.", repo.WordPressInstallation.UserLoginInfo, new RecordItemIndex(3));
            //repo.WordPressInstallation.UserLogin.Element.SetAttributeValue("Value", "rx");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rx' with focus on 'WordPressInstallation.UserLogin'.", repo.WordPressInstallation.UserLoginInfo, new RecordItemIndex(4));
            repo.WordPressInstallation.UserLogin.PressKeys("rx");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'WordPressInstallation.PassStrengthResult'", repo.WordPressInstallation.PassStrengthResultInfo, new ActionTimeout(5000), new RecordItemIndex(5));
            repo.WordPressInstallation.PassStrengthResultInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Value to '' on item 'WordPressInstallation.Pass1Text'.", repo.WordPressInstallation.Pass1TextInfo, new RecordItemIndex(6));
            repo.WordPressInstallation.Pass1Text.Element.SetAttributeValue("Value", "");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(7));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.Pass1Text' at Center.", repo.WordPressInstallation.Pass1TextInfo, new RecordItemIndex(8));
            repo.WordPressInstallation.Pass1Text.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'r' with focus on 'WordPressInstallation.Pass1Text'.", repo.WordPressInstallation.Pass1TextInfo, new RecordItemIndex(9));
            repo.WordPressInstallation.Pass1Text.PressKeys("r");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'x' with focus on 'WordPressInstallation.Pass1Text'.", repo.WordPressInstallation.Pass1TextInfo, new RecordItemIndex(10));
            repo.WordPressInstallation.Pass1Text.PressKeys("x");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.PwWeak' at Center.", repo.WordPressInstallation.PwWeakInfo, new RecordItemIndex(11));
            repo.WordPressInstallation.PwWeak.Click();
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Value to 'xy@ranorex.com' on item 'WordPressInstallation.AdminEmail'.", repo.WordPressInstallation.AdminEmailInfo, new RecordItemIndex(12));
            repo.WordPressInstallation.AdminEmail.Element.SetAttributeValue("Value", "xy@ranorex.com");
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPressInstallation.Self, false, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.Submit' at Center.", repo.WordPressInstallation.SubmitInfo, new RecordItemIndex(14));
            repo.WordPressInstallation.Submit.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Success!') on item 'WordPressInstallation.Success'.", repo.WordPressInstallation.SuccessInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.WordPressInstallation.SuccessInfo, "InnerText", "Success!");
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPressInstallation.Self, false, new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.LogIn' at Center.", repo.WordPressInstallation.LogInInfo, new RecordItemIndex(17));
            repo.WordPressInstallation.LogIn.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
