///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WPDockerDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WPDockerDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("3c94c518-798a-4021-a8b1-40b618b7b892")]
    public partial class WPDockerDemoRepository : RepoGenBaseFolder
    {
        static WPDockerDemoRepository instance = new WPDockerDemoRepository();
        WPDockerDemoRepositoryFolders.WordPressInstallationAppFolder _wordpressinstallation;

        /// <summary>
        /// Gets the singleton class instance representing the WPDockerDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("3c94c518-798a-4021-a8b1-40b618b7b892")]
        public static WPDockerDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WPDockerDemoRepository() 
            : base("WPDockerDemoRepository", "/", null, 0, false, "3c94c518-798a-4021-a8b1-40b618b7b892", ".\\RepositoryImages\\WPDockerDemoRepository3c94c518.rximgres")
        {
            _wordpressinstallation = new WPDockerDemoRepositoryFolders.WordPressInstallationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3c94c518-798a-4021-a8b1-40b618b7b892")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WordPressInstallation folder.
        /// </summary>
        [RepositoryFolder("a6a403cf-f8e5-47e4-9841-d297ef98d8ed")]
        public virtual WPDockerDemoRepositoryFolders.WordPressInstallationAppFolder WordPressInstallation
        {
            get { return _wordpressinstallation; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class WPDockerDemoRepositoryFolders
    {
        /// <summary>
        /// The WordPressInstallationAppFolder folder.
        /// </summary>
        [RepositoryFolder("a6a403cf-f8e5-47e4-9841-d297ef98d8ed")]
        public partial class WordPressInstallationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _englishunitedstatesInfo;
            RepoItemInfo _languagecontinueInfo;
            RepoItemInfo _weblogtitleInfo;
            RepoItemInfo _userloginInfo;
            RepoItemInfo _pass1textInfo;
            RepoItemInfo _pwweakInfo;
            RepoItemInfo _adminemailInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _successInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _userpassInfo;
            RepoItemInfo _wpsubmitInfo;
            RepoItemInfo _welcometowordpressInfo;
            RepoItemInfo _howdyrxInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _ptagyouarenowloggedoutInfo;
            RepoItemInfo _passstrengthresultInfo;

            /// <summary>
            /// Creates a new WordPressInstallation  folder.
            /// </summary>
            public WordPressInstallationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WordPressInstallation", "/dom[@domain~'.*:.*']", parentFolder, 8000, null, false, "a6a403cf-f8e5-47e4-9841-d297ef98d8ed", "")
            {
                _englishunitedstatesInfo = new RepoItemInfo(this, "EnglishUnitedStates", ".//select[#'language']/option[@value='']", 30000, null, "d8bfbf41-c246-47a9-af7a-1a8a216f50cb");
                _languagecontinueInfo = new RepoItemInfo(this, "LanguageContinue", ".//input[#'language-continue']", 30000, null, "ca7b1c39-1e27-498e-b356-abd65b4c07f7");
                _weblogtitleInfo = new RepoItemInfo(this, "WeblogTitle", ".//input[#'weblog_title']", 30000, null, "4cc5b9ca-ab63-434d-a6fd-ab4dccce1b4c");
                _userloginInfo = new RepoItemInfo(this, "UserLogin", ".//input[#'user_login']", 30000, null, "604c0f23-0fd5-4c67-bf48-692ad18c2560");
                _pass1textInfo = new RepoItemInfo(this, "Pass1Text", ".//input[#'pass1-text']", 30000, null, "55fa5f09-747e-4897-8aef-827aab6784c2");
                _pwweakInfo = new RepoItemInfo(this, "PwWeak", ".//form[#'setup']/table/tbody/tr[5]/td/label/input[@name='pw_weak' and @visible='True']", 30000, null, "946daa33-1b14-41da-b29a-32734db25b18");
                _adminemailInfo = new RepoItemInfo(this, "AdminEmail", ".//input[#'admin_email']", 30000, null, "e8dba429-aa0c-4b47-9b3d-bfa7512339ca");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "eb022295-f2b6-4107-a937-48c863a98d62");
                _successInfo = new RepoItemInfo(this, "Success", "?/?/h1[@innertext='Success!']", 30000, null, "7d660776-6d49-48fe-827a-3610ad0d73c0");
                _loginInfo = new RepoItemInfo(this, "LogIn", "body/p[3]/a[@innertext='Log In']", 30000, null, "3a84d307-1ee3-48cc-9420-58e5ebfd599b");
                _userpassInfo = new RepoItemInfo(this, "UserPass", ".//input[#'user_pass']", 30000, null, "948af896-337f-4e37-a1cc-3a9f72a8aadf");
                _wpsubmitInfo = new RepoItemInfo(this, "WpSubmit", ".//input[#'wp-submit']", 30000, null, "db410340-67ea-4be6-97ea-dac6855f3689");
                _welcometowordpressInfo = new RepoItemInfo(this, "WelcomeToWordPress", ".//div[#'welcome-panel']/div/h2[@innertext='Welcome to WordPress!']", 30000, null, "4bd5bf58-1560-40e9-9827-0e20e63c81ff");
                _howdyrxInfo = new RepoItemInfo(this, "HowdyRx", ".//li[#'wp-admin-bar-my-account']", 30000, null, "54063121-c91b-4af0-a8c2-0489e05044e1");
                _logoutInfo = new RepoItemInfo(this, "LogOut", ".//li[#'wp-admin-bar-logout']/a[@innertext='Log Out']", 30000, null, "c727fddb-8945-4677-b228-1aeea4e1c0de");
                _ptagyouarenowloggedoutInfo = new RepoItemInfo(this, "PTagYouAreNowLoggedOut", ".//div[#'login']/p[@innertext='You are now logged out.']", 30000, null, "59989d21-0978-44f1-986b-790b5968d794");
                _passstrengthresultInfo = new RepoItemInfo(this, "PassStrengthResult", ".//div[@id='pass-strength-result' and @visible='true']", 30000, null, "f1ca132d-8f94-4481-adad-b74fd74f8859");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a6a403cf-f8e5-47e4-9841-d297ef98d8ed")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6a403cf-f8e5-47e4-9841-d297ef98d8ed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnglishUnitedStates item.
            /// </summary>
            [RepositoryItem("d8bfbf41-c246-47a9-af7a-1a8a216f50cb")]
            public virtual Ranorex.OptionTag EnglishUnitedStates
            {
                get
                {
                    return _englishunitedstatesInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The EnglishUnitedStates item info.
            /// </summary>
            [RepositoryItemInfo("d8bfbf41-c246-47a9-af7a-1a8a216f50cb")]
            public virtual RepoItemInfo EnglishUnitedStatesInfo
            {
                get
                {
                    return _englishunitedstatesInfo;
                }
            }

            /// <summary>
            /// The LanguageContinue item.
            /// </summary>
            [RepositoryItem("ca7b1c39-1e27-498e-b356-abd65b4c07f7")]
            public virtual Ranorex.InputTag LanguageContinue
            {
                get
                {
                    return _languagecontinueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LanguageContinue item info.
            /// </summary>
            [RepositoryItemInfo("ca7b1c39-1e27-498e-b356-abd65b4c07f7")]
            public virtual RepoItemInfo LanguageContinueInfo
            {
                get
                {
                    return _languagecontinueInfo;
                }
            }

            /// <summary>
            /// The WeblogTitle item.
            /// </summary>
            [RepositoryItem("4cc5b9ca-ab63-434d-a6fd-ab4dccce1b4c")]
            public virtual Ranorex.InputTag WeblogTitle
            {
                get
                {
                    return _weblogtitleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WeblogTitle item info.
            /// </summary>
            [RepositoryItemInfo("4cc5b9ca-ab63-434d-a6fd-ab4dccce1b4c")]
            public virtual RepoItemInfo WeblogTitleInfo
            {
                get
                {
                    return _weblogtitleInfo;
                }
            }

            /// <summary>
            /// The UserLogin item.
            /// </summary>
            [RepositoryItem("604c0f23-0fd5-4c67-bf48-692ad18c2560")]
            public virtual Ranorex.InputTag UserLogin
            {
                get
                {
                    return _userloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserLogin item info.
            /// </summary>
            [RepositoryItemInfo("604c0f23-0fd5-4c67-bf48-692ad18c2560")]
            public virtual RepoItemInfo UserLoginInfo
            {
                get
                {
                    return _userloginInfo;
                }
            }

            /// <summary>
            /// The Pass1Text item.
            /// </summary>
            [RepositoryItem("55fa5f09-747e-4897-8aef-827aab6784c2")]
            public virtual Ranorex.InputTag Pass1Text
            {
                get
                {
                    return _pass1textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Pass1Text item info.
            /// </summary>
            [RepositoryItemInfo("55fa5f09-747e-4897-8aef-827aab6784c2")]
            public virtual RepoItemInfo Pass1TextInfo
            {
                get
                {
                    return _pass1textInfo;
                }
            }

            /// <summary>
            /// The PwWeak item.
            /// </summary>
            [RepositoryItem("946daa33-1b14-41da-b29a-32734db25b18")]
            public virtual Ranorex.InputTag PwWeak
            {
                get
                {
                    return _pwweakInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PwWeak item info.
            /// </summary>
            [RepositoryItemInfo("946daa33-1b14-41da-b29a-32734db25b18")]
            public virtual RepoItemInfo PwWeakInfo
            {
                get
                {
                    return _pwweakInfo;
                }
            }

            /// <summary>
            /// The AdminEmail item.
            /// </summary>
            [RepositoryItem("e8dba429-aa0c-4b47-9b3d-bfa7512339ca")]
            public virtual Ranorex.InputTag AdminEmail
            {
                get
                {
                    return _adminemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AdminEmail item info.
            /// </summary>
            [RepositoryItemInfo("e8dba429-aa0c-4b47-9b3d-bfa7512339ca")]
            public virtual RepoItemInfo AdminEmailInfo
            {
                get
                {
                    return _adminemailInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("eb022295-f2b6-4107-a937-48c863a98d62")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("eb022295-f2b6-4107-a937-48c863a98d62")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Success item.
            /// </summary>
            [RepositoryItem("7d660776-6d49-48fe-827a-3610ad0d73c0")]
            public virtual Ranorex.H1Tag Success
            {
                get
                {
                    return _successInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Success item info.
            /// </summary>
            [RepositoryItemInfo("7d660776-6d49-48fe-827a-3610ad0d73c0")]
            public virtual RepoItemInfo SuccessInfo
            {
                get
                {
                    return _successInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("3a84d307-1ee3-48cc-9420-58e5ebfd599b")]
            public virtual Ranorex.ATag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("3a84d307-1ee3-48cc-9420-58e5ebfd599b")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The UserPass item.
            /// </summary>
            [RepositoryItem("948af896-337f-4e37-a1cc-3a9f72a8aadf")]
            public virtual Ranorex.InputTag UserPass
            {
                get
                {
                    return _userpassInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPass item info.
            /// </summary>
            [RepositoryItemInfo("948af896-337f-4e37-a1cc-3a9f72a8aadf")]
            public virtual RepoItemInfo UserPassInfo
            {
                get
                {
                    return _userpassInfo;
                }
            }

            /// <summary>
            /// The WpSubmit item.
            /// </summary>
            [RepositoryItem("db410340-67ea-4be6-97ea-dac6855f3689")]
            public virtual Ranorex.InputTag WpSubmit
            {
                get
                {
                    return _wpsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WpSubmit item info.
            /// </summary>
            [RepositoryItemInfo("db410340-67ea-4be6-97ea-dac6855f3689")]
            public virtual RepoItemInfo WpSubmitInfo
            {
                get
                {
                    return _wpsubmitInfo;
                }
            }

            /// <summary>
            /// The WelcomeToWordPress item.
            /// </summary>
            [RepositoryItem("4bd5bf58-1560-40e9-9827-0e20e63c81ff")]
            public virtual Ranorex.H2Tag WelcomeToWordPress
            {
                get
                {
                    return _welcometowordpressInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The WelcomeToWordPress item info.
            /// </summary>
            [RepositoryItemInfo("4bd5bf58-1560-40e9-9827-0e20e63c81ff")]
            public virtual RepoItemInfo WelcomeToWordPressInfo
            {
                get
                {
                    return _welcometowordpressInfo;
                }
            }

            /// <summary>
            /// The HowdyRx item.
            /// </summary>
            [RepositoryItem("54063121-c91b-4af0-a8c2-0489e05044e1")]
            public virtual Ranorex.LiTag HowdyRx
            {
                get
                {
                    return _howdyrxInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The HowdyRx item info.
            /// </summary>
            [RepositoryItemInfo("54063121-c91b-4af0-a8c2-0489e05044e1")]
            public virtual RepoItemInfo HowdyRxInfo
            {
                get
                {
                    return _howdyrxInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("c727fddb-8945-4677-b228-1aeea4e1c0de")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("c727fddb-8945-4677-b228-1aeea4e1c0de")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The PTagYouAreNowLoggedOut item.
            /// </summary>
            [RepositoryItem("59989d21-0978-44f1-986b-790b5968d794")]
            public virtual Ranorex.PTag PTagYouAreNowLoggedOut
            {
                get
                {
                    return _ptagyouarenowloggedoutInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagYouAreNowLoggedOut item info.
            /// </summary>
            [RepositoryItemInfo("59989d21-0978-44f1-986b-790b5968d794")]
            public virtual RepoItemInfo PTagYouAreNowLoggedOutInfo
            {
                get
                {
                    return _ptagyouarenowloggedoutInfo;
                }
            }

            /// <summary>
            /// The PassStrengthResult item.
            /// </summary>
            [RepositoryItem("f1ca132d-8f94-4481-adad-b74fd74f8859")]
            public virtual Ranorex.DivTag PassStrengthResult
            {
                get
                {
                    return _passstrengthresultInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PassStrengthResult item info.
            /// </summary>
            [RepositoryItemInfo("f1ca132d-8f94-4481-adad-b74fd74f8859")]
            public virtual RepoItemInfo PassStrengthResultInfo
            {
                get
                {
                    return _passstrengthresultInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}